### ISSUE TITLE
[Request] Track/Playlist Feature Chart

### ISSUE THREAD

**Issue by M-Barrows** [hannahilea/2021-mix-of-the-month-club#1]
It might be fun to display the Feature Characteristics for a monthly playlist. Something like the image below. This is a completely frivolous request though and the site is great already :) 

![](https://i.redd.it/6rcyni2t8a451.png)

**Comment by hannahilea** [comment]
Feel free to open a PR that implements this! :joy:

**Comment by hannahilea** [comment]
Implemented as of #2 / #4 !
